---
# install, uninstall, start, stop, restart     #/upgrade/update

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "started"
    docker_container_restart: false
    docker_container_recreate: false
  tags: ['install', 'start', 'update']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "present"
    docker_container_restart: false
    docker_container_recreate: true
  tags: ['recreate']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "stopped"
    docker_container_restart: false
    docker_container_recreate: false
  tags: ['stop']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "started"
    docker_container_restart: true
    docker_container_recreate: false
  tags: ['restart']

- name: main | set fact docker_container_state
  ansible.builtin.set_fact:
    docker_container_state: "absent"
    docker_container_restart: false
    docker_container_recreate: false
  tags: ['uninstall','destory']

- name: main | login dockerhub, pull latest image and delete the expired image
  import_tasks: image.yml

- name: main | deploy with docker
  import_tasks: container.yml